security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            remember_me:
                secret:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: worldbreakersdb_index
                use_referer: true
            anonymous: ~
            logout:
                invalidate_session: true
                success_handler: logout.redirect
            logout_on_user_change: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/../deck/view/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/../deck/, role: ROLE_USER }
        - { path: ^/../decks, role: ROLE_USER }
        - { path: ^/../user/, role: ROLE_USER }
