services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $tempDir: '%kernel.project_dir%/var'
            $publicDir: '%kernel.project_dir%/web'

    logout.redirect:
        class: AppBundle\Controller\RedirectAfterLogout

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Behavior,DataFixtures,DQL,Entity,Repository,Resources}'

    AppBundle\EventListener\DecklistListener:
        tags:
            - { name: doctrine.event_listener, entity: AppBundle\Entity\Decklist, event: postPersist }
            - { name: doctrine.event_listener, entity: AppBundle\Entity\Decklist, event: postUpdate }
            - { name: doctrine.event_listener, entity: AppBundle\Entity\Decklist, event: postRemove }
