AppBundle\Entity\Card:
    type: entity
    table: card
    repositoryClass: AppBundle\Repository\CardRepository
    indexes:
        title_index:
            columns: [ title ]
        cost_index:
            columns: [ cost ]
        strength_index:
            columns: [ strength ]
    manyToOne:
        pack:
            targetEntity: Pack
            inversedBy: cards
            joinColumn:
                name: pack_id
                referencedColumnName: id
        type:
            targetEntity: Type
            inversedBy: cards
            joinColumn:
                name: type_id
                referencedColumnName: id
        faction:
            targetEntity: Faction
            inversedBy: cards
            joinColumn:
                name: faction_id
                referencedColumnName: id
    oneToMany:
        decklists:
            targetEntity: Decklist
            orderBy: {'dateCreation':'DESC'}
            mappedBy: identity
        reviews:
            targetEntity: Review
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
        rulings:
            targetEntity: Ruling
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on:  update
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        code:
            type: string
            unique: true
            length: 5
        title:
            type: string
            length: 255
        strippedTitle:
            type: string
            length: '1024'
            nullable: true
        keywords:
            type: string
            length: 255
            nullable: true
        text:
            type: string
            length: '1024'
            nullable: true
        strippedText:
            type: string
            length: '1024'
            nullable: true
        cost:
            type: smallint
            nullable: true
        flavor:
            type: string
            length: '1024'
            nullable: true
        illustrator:
            type: string
            length: 255
            nullable: true
        position:
            type: smallint
            nullable: false
        strength:
            type: smallint
            nullable: true
        health:
            type: smallint
            nullable: true
        stages:
            type: array
            nullable: true
        standing:
            type: json
            column: 'standing'
            nullable: true
        standingReq:
            type: smallint
            column: 'standing_req'
            nullable: true
        signature:
            type: string
            length: 255
            nullable: true
        imageUrl:
            type: string
            column: image_url
            nullable: true
    lifecycleCallbacks: {  }
